CREATE TABLE IF NOT EXISTS "Statuses" ("ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"Name" varchar(50) NOT NULL,"Description" varchar(150));
CREATE TABLE IF NOT EXISTS "Users" ("ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"Name" varchar(50) NOT NULL,"Description" varchar(150) NOT NULL,"Email" varchar(50) NOT NULL,"Password" varchar(100) NOT NULL,"Department" varchar(50) NOT NULL,"JobTitle" varchar(50) NOT NULL,"CreatedOn" timestamptz NOT NULL,"ModifiedOn" timestamptz,"StatusID" integer NOT NULL REFERENCES "Statuses"("ID"));
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON "Users" (lower("Email"));

CREATE TABLE IF NOT EXISTS "Roles" ("ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"Name" varchar(50) NOT NULL,"Description" varchar(150),"CreatedOn" timestamptz NOT NULL,"ModifiedOn" timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS ux_roles_name ON "Roles"("Name");
CREATE TABLE IF NOT EXISTS "Permissions" ("ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"Name" varchar(50) NOT NULL,"Description" varchar(150),"Tag" varchar(50) NOT NULL,"Resource" varchar(50) NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS ux_permissions_tag ON "Permissions"("Tag");
CREATE TABLE IF NOT EXISTS "UserRoles" ("ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"UserID" bigint NOT NULL REFERENCES "Users"("ID") ON DELETE CASCADE,"RoleID" bigint NOT NULL REFERENCES "Roles"("ID") ON DELETE CASCADE,UNIQUE("UserID","RoleID"));
CREATE INDEX IF NOT EXISTS ix_user_roles_user ON "UserRoles"("UserID");
CREATE TABLE IF NOT EXISTS "RolePermissions" ("ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"RoleID" bigint NOT NULL REFERENCES "Roles"("ID") ON DELETE CASCADE,"PermissionID" bigint NOT NULL REFERENCES "Permissions"("ID") ON DELETE CASCADE,UNIQUE("RoleID","PermissionID"));
CREATE INDEX IF NOT EXISTS ix_role_permissions_role ON "RolePermissions"("RoleID");

CREATE TABLE IF NOT EXISTS "Projects" ("ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"Name" varchar(50) NOT NULL,"Description" varchar(100),"CreatedOn" timestamptz NOT NULL,"ModifiedOn" timestamptz,"StartDate" timestamptz NOT NULL,"TargetDate" timestamptz NOT NULL,"PriorityLevel" integer NOT NULL,"StatusID" integer NOT NULL REFERENCES "Statuses"("ID"),"UserID" bigint NOT NULL REFERENCES "Users"("ID"));
CREATE INDEX IF NOT EXISTS ix_projects_user ON "Projects"("UserID");
CREATE TABLE IF NOT EXISTS "Stages" ("ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"Name" varchar(50) NOT NULL,"Description" varchar(50));
CREATE TABLE IF NOT EXISTS "Tasks" ("ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"Name" varchar(50) NOT NULL,"Description" varchar(50),"CreatedOn" timestamptz NOT NULL,"ModifiedOn" timestamptz,"StatusID" integer NOT NULL REFERENCES "Statuses"("ID"),"ProjectID" bigint NOT NULL REFERENCES "Projects"("ID"),"UserID" bigint NOT NULL REFERENCES "Users"("ID"),"StageID" integer NOT NULL REFERENCES "Stages"("ID"),"AssignedUserID" bigint NOT NULL REFERENCES "Users"("ID"),"Priority" integer NOT NULL,"DueDate" timestamptz);
CREATE TABLE IF NOT EXISTS "Comments" ("ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"Text" varchar(500) NOT NULL,"TaskID" bigint NOT NULL,"UserID" bigint NOT NULL,"CreatedOn" timestamptz NOT NULL,"ModifiedOn" timestamptz);
CREATE TABLE IF NOT EXISTS "Audits" ("ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"UserID" bigint NOT NULL REFERENCES "Users"("ID"),"EventID" integer NOT NULL,"ActionID" integer NOT NULL,"CreatedOn" timestamptz NOT NULL,"BeforeWas" text NOT NULL,"AfterIs" text NOT NULL,"StatusID" integer NOT NULL);

INSERT INTO "Statuses"("ID","Name","Description") VALUES (1,'ACTIVE','Active') ON CONFLICT ("ID") DO NOTHING;
INSERT INTO "Roles"("Name","Description","CreatedOn") VALUES ('MEMBER','Default project member',CURRENT_TIMESTAMP) ON CONFLICT ("Name") DO NOTHING;
INSERT INTO "Permissions"("Name","Description","Tag","Resource") VALUES
 ('Create project','Create owned projects','project:create','project'),
 ('Read project','Read owned projects','project:read','project'),
 ('Update project','Update owned projects','project:update','project') ON CONFLICT ("Tag") DO NOTHING;
INSERT INTO "RolePermissions"("RoleID","PermissionID") SELECT r."ID",p."ID" FROM "Roles" r CROSS JOIN "Permissions" p WHERE r."Name"='MEMBER' AND p."Tag" IN ('project:create','project:read','project:update') ON CONFLICT ("RoleID","PermissionID") DO NOTHING;
